#
# Makefile for octave's libcruft/lapack-xtra directory
#
# John W. Eaton
# jwe@bevo.che.wisc.edu
# University of Wisconsin-Madison
# Department of Chemical Engineering

TOPDIR = ../..

srcdir = .
top_srcdir = ../..


EXTERNAL_DISTFILES = $(DISTFILES)

include $(TOPDIR)/Makeconf

include ../Makerules
