// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_mx_cdm_m_h)
#define octave_mx_cdm_m_h 1
#include "CMatrix.h"
#include "CDiagMatrix.h"
#include "dMatrix.h"
#include "mx-op-defs.h"
DMM_OP_DECLS (ComplexMatrix, ComplexDiagMatrix, Matrix)
#endif
