// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_mx_cdm_cm_h)
#define octave_mx_cdm_cm_h 1
#include "CMatrix.h"
#include "CDiagMatrix.h"
#include "mx-op-defs.h"
DMM_OP_DECLS (ComplexMatrix, ComplexDiagMatrix, ComplexMatrix)
#endif
