// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_mx_cm_s_h)
#define octave_mx_cm_s_h 1
#include "CMatrix.h"
#include "mx-op-defs.h"
MS_OP_DECLS (ComplexMatrix, ComplexMatrix, double)
#endif
