// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "mx-cm-m.h"
#include "boolMatrix.h"
#include "CMatrix.h"
#include "dMatrix.h"
MM_BIN_OPS (ComplexMatrix, ComplexMatrix, Matrix)
MM_CMP_OPS (ComplexMatrix, real, Matrix, )
MM_BOOL_OPS (ComplexMatrix, Matrix, 0.0)
