// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_mx_cdm_dm_h)
#define octave_mx_cdm_dm_h 1
#include "CDiagMatrix.h"
#include "dDiagMatrix.h"
#include "mx-op-defs.h"
DMDM_OP_DECLS (ComplexDiagMatrix, ComplexDiagMatrix, DiagMatrix)
#endif
