// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_mx_cnda_s_h)
#define octave_mx_cnda_s_h 1
#include "CNDArray.h"
#include "mx-op-defs.h"
NDS_OP_DECLS (ComplexNDArray, ComplexNDArray, double)
#endif
