// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_mx_cnda_nda_h)
#define octave_mx_cnda_nda_h 1
#include "CNDArray.h"
#include "dNDArray.h"
#include "mx-op-defs.h"
NDND_OP_DECLS (ComplexNDArray, ComplexNDArray, NDArray)
#endif
