// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_mx_cdm_s_h)
#define octave_mx_cdm_s_h 1
#include "CMatrix.h"
#include "CDiagMatrix.h"
#include "mx-op-defs.h"
DMS_OP_DECLS (ComplexMatrix, ComplexDiagMatrix, double)
#endif
