// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_mx_cs_m_h)
#define octave_mx_cs_m_h 1
#include "CMatrix.h"
#include "oct-cmplx.h"
#include "dMatrix.h"
#include "mx-op-defs.h"
SM_OP_DECLS (ComplexMatrix, Complex, Matrix)
#endif
