// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "mx-cnda-s.h"
#include "boolMatrix.h"
#include "boolNDArray.h"
#include "CNDArray.h"
NDS_BIN_OPS (ComplexNDArray, ComplexNDArray, double)
NDS_CMP_OPS (ComplexNDArray, real, double, )
NDS_BOOL_OPS (ComplexNDArray, double, 0.0)
