// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_mx_cs_dm_h)
#define octave_mx_cs_dm_h 1
#include "CMatrix.h"
#include "oct-cmplx.h"
#include "dDiagMatrix.h"
#include "mx-op-defs.h"
SDM_OP_DECLS (ComplexMatrix, Complex, DiagMatrix)
#endif
