// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_mx_cs_nda_h)
#define octave_mx_cs_nda_h 1
#include "CNDArray.h"
#include "oct-cmplx.h"
#include "dNDArray.h"
#include "mx-op-defs.h"
SND_OP_DECLS (ComplexNDArray, Complex, NDArray)
#endif
