// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_mx_cm_dm_h)
#define octave_mx_cm_dm_h 1
#include "CMatrix.h"
#include "dDiagMatrix.h"
#include "mx-op-defs.h"
MDM_OP_DECLS (ComplexMatrix, ComplexMatrix, DiagMatrix)
#endif
