// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_mx_cm_m_h)
#define octave_mx_cm_m_h 1
#include "CMatrix.h"
#include "dMatrix.h"
#include "mx-op-defs.h"
MM_OP_DECLS (ComplexMatrix, ComplexMatrix, Matrix)
#endif
