// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_mx_dm_cs_h)
#define octave_mx_dm_cs_h 1
#include "CMatrix.h"
#include "dDiagMatrix.h"
#include "oct-cmplx.h"
#include "mx-op-defs.h"
DMS_OP_DECLS (ComplexMatrix, DiagMatrix, Complex)
#endif
