// DO NOT EDIT -- generated by mk-ops
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "Array-util.h"
#include "mx-dm-cdm.h"
#include "CDiagMatrix.h"
#include "dDiagMatrix.h"
DMDM_BIN_OPS (ComplexDiagMatrix, DiagMatrix, ComplexDiagMatrix)
