// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_mx_dm_m_h)
#define octave_mx_dm_m_h 1
#include "dMatrix.h"
#include "dDiagMatrix.h"
#include "mx-op-defs.h"
DMM_OP_DECLS (Matrix, DiagMatrix, Matrix)
#endif
