// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_mx_dm_s_h)
#define octave_mx_dm_s_h 1
#include "dMatrix.h"
#include "dDiagMatrix.h"
#include "mx-op-defs.h"
DMS_OP_DECLS (Matrix, DiagMatrix, double)
#endif
