// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_mx_m_cm_h)
#define octave_mx_m_cm_h 1
#include "CMatrix.h"
#include "dMatrix.h"
#include "mx-op-defs.h"
MM_OP_DECLS (ComplexMatrix, Matrix, ComplexMatrix)
#endif
