// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_mx_m_cs_h)
#define octave_mx_m_cs_h 1
#include "CMatrix.h"
#include "dMatrix.h"
#include "oct-cmplx.h"
#include "mx-op-defs.h"
MS_OP_DECLS (ComplexMatrix, Matrix, Complex)
#endif
