// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_mx_m_dm_h)
#define octave_mx_m_dm_h 1
#include "dMatrix.h"
#include "dDiagMatrix.h"
#include "mx-op-defs.h"
MDM_OP_DECLS (Matrix, Matrix, DiagMatrix)
#endif
