// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_mx_nda_cs_h)
#define octave_mx_nda_cs_h 1
#include "CNDArray.h"
#include "dNDArray.h"
#include "oct-cmplx.h"
#include "mx-op-defs.h"
NDS_OP_DECLS (ComplexNDArray, NDArray, Complex)
#endif
