// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_mx_nda_cnda_h)
#define octave_mx_nda_cnda_h 1
#include "CNDArray.h"
#include "dNDArray.h"
#include "mx-op-defs.h"
NDND_OP_DECLS (ComplexNDArray, NDArray, ComplexNDArray)
#endif
