// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_mx_s_cm_h)
#define octave_mx_s_cm_h 1
#include "CMatrix.h"
#include "mx-op-defs.h"
SM_OP_DECLS (ComplexMatrix, double, ComplexMatrix)
#endif
