// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_mx_s_cnda_h)
#define octave_mx_s_cnda_h 1
#include "CNDArray.h"
#include "mx-op-defs.h"
SND_OP_DECLS (ComplexNDArray, double, ComplexNDArray)
#endif
