// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_vx_crv_rv_h)
#define octave_vx_crv_rv_h 1
#include "CRowVector.h"
#include "dRowVector.h"
#include "mx-op-defs.h"
VV_OP_DECLS (ComplexRowVector, ComplexRowVector, RowVector)
#endif
