// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_vx_crv_s_h)
#define octave_vx_crv_s_h 1
#include "CRowVector.h"
#include "mx-op-defs.h"
VS_OP_DECLS (ComplexRowVector, ComplexRowVector, double)
#endif
