// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_vx_ccv_s_h)
#define octave_vx_ccv_s_h 1
#include "CColVector.h"
#include "mx-op-defs.h"
VS_OP_DECLS (ComplexColumnVector, ComplexColumnVector, double)
#endif
