// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_vx_cs_rv_h)
#define octave_vx_cs_rv_h 1
#include "CRowVector.h"
#include "oct-cmplx.h"
#include "dRowVector.h"
#include "mx-op-defs.h"
SV_OP_DECLS (ComplexRowVector, Complex, RowVector)
#endif
