// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_vx_s_crv_h)
#define octave_vx_s_crv_h 1
#include "CRowVector.h"
#include "mx-op-defs.h"
SV_OP_DECLS (ComplexRowVector, double, ComplexRowVector)
#endif
